/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d9fa152e-2cd6-4470-9d72-41640f7f4b54",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_s5RUmNOzD",
    "aws_user_pools_web_client_id": "3prj3o91fmotfvksbm17s7cjj7",
    "oauth": {},
    "aws_user_files_s3_bucket": "chatui90ad62ea696c4b5cb53ee2d968aca9b195908-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pcnblqkvrvdnpllk2i4xhlr37m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
